---
- apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present
- apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present
- apt: name={{item}} state=latest
  with_items: [ libxcb-keysyms1, hipchat ]
